apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-api-java-deployment
spec:
  replicas: 2 # Vamos subir duas instâncias da nossa API
  selector:
    matchLabels:
      app: minha-api-java
  template:
    metadata:
      labels:
        app: minha-api-java
    spec:
      containers:
      - name: minha-api-java
        image: api-java:v1
        imagePullPolicy: IfNotPresent # Para usar a imagem local
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: meu-servico-java
spec:
  type: NodePort
  selector:
    app: minha-api-java
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001 # Porta que será exposta para acesso externo